export {
  AUTH_TOKEN_COOKIE,
  AUTH_USER_COOKIE,
  type SessionUser,
  type CookieWriteOptions,
  getClientToken,
  getClientUser,
  getClientSession,
  setClientSession,
  setClientToken,
  setClientUser,
  clearClientSession,
  getServerToken,
  getServerUser,
  getServerSession,
  setServerSession,
  clearServerSession,
  hasRole,
} from "./session";

export {
  requireAuth,
  requireRole,
  requireAdmin,
  requireSuperAdmin,
  requireCustomer,
  getOptionalAuth,
  type AuthContext,
  type RequireAuthOptions,
} from "./requireAuth";
